### ISSUE TITLE
idea: create-anywidget

### ISSUE THREAD

**Issue by manzt** [Octoframes/anywidget-minimal-react-template#3]
Following our discussion here, I have been experimenting with a CLI for bootstrapping anywidget projects. I published a prototype to npm:

```
npm create anywidget@latest ipyfoo
```

```
ipyfoo
├── js
│  ├── package.json
│  ├── styles.css
│  └── widget.jsx
├── pyproject.toml
├── README.md
└── src
   └── ipyfoo
      └── __init__.py
```

branch is here if you are curious: https://github.com/manzt/anywidget/tree/create-anywidget

**Comment by manzt** [comment]
Again, want to avoid cookiecutters so not sure if this is a sustainable approach. But maybe the config is simple enough (famous last words).

**Comment by kolibril13** [comment]
Awesome, I just checked and `npm create anywidget@latest ipyfoo`works great.

**First thought** :
 `npm create anywidget@latest` works also in a cwd, but not when I already have a git archive in my folder initialized:
<img width="1582" alt="image" src="https://github.com/Octoframes/anywidget-minimal-react-template/assets/44469195/ab350b29-7c4d-43a3-bbf9-cc323bb722d8">
When I continue, I get the error:

```
◇  Directory not empty.
Continue?
│  Yes
│
◇  Which anywidget template?
│  react
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: EACCES: permission denied, open '.git/objects/3e/c69d032677cdb0e4bf3d327d6722fe1f2c5600'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '.git/objects/3e/c69d032677cdb0e4bf3d327d6722fe1f2c5600'
}

Node.js v18.14.0
npm ERR! code 1
npm ERR! path /Users/jan-hendrik/projects/okapi
npm ERR! command failed
npm ERR! command sh -c create-anywidget
```

not a big problem, but maybe there's an easy solution for that.

**Second thought:** 
I think that `package.json` should live in root, and not in the js folder.
This would make development more frictionless as there won't be any `cd js` and `cd ..` in the development cycle.
I ran into problems where  I installed my .venv by accident in the js folder and then VS Code was not able to find it there. 
(from https://github.com/kolibril13/ipymafs/pull/3#issuecomment-1646560286)

**Comment by manzt** [comment]
> npm create anywidget@latest works also in a cwd, but not when I already have a git archive in my folder initialized:

Oops! This is actually a good thing. I think this is related to the code I wrote to rename the `my_widget` across files in the project. It seems `my_widget` is in this git history and my code would have corrupted the git history (not good). We only want to try to rename files/paths _within_ the template and not anything else that was provided before. Maybe there is a nicer way to do this without touching the filesystem.

> I think that package.json should live in root, and not in the js folder.

Ahh interesting. I think that makes sense. The commands to get started would need to be updated accordingly, but should be a simple fix.

**Comment by kolibril13** [comment]
that might be the case.
Actually, after running `npm create anywidget@latest` there are some files generated, one of them is `_gitignore` (not .gitignore) and the version control is afterward completely broken:
<img width="1505" alt="image" src="https://github.com/Octoframes/anywidget-minimal-react-template/assets/44469195/8dbc50eb-3adf-447c-8333-00be3e9e1d73">
I had to delete the project locally completely and re-download it from github and now git is working again :D

> Ahh interesting. I think that makes sense. The commands to get started would need to be updated accordingly, but should be a simple fix.

glad you like this idea! :)

**Comment by manzt** [comment]
> I had to delete the project locally completely and re-download it from github and now git is working again 🫥 

oof yes, very sorry about that. My find and replace code must have corrupted the git history. Would have been VERY bad if you had local branches you needed. I'm at a conference right now so please avoid running (in a hit directory at least) again until i'm able to push out a fix. Thanks for your patience and ideas :)

**Comment by kolibril13** [comment]
Actually, that was a good learning lesson!
I always thought git archives are somehow protected and can not be damaged by some search and replace action, but very good to know that they can.
I'm normally pushing my branches to GH and I do regular backups on an external drive, so I did not lose any data.
But e.g. when running `npm create anywidget@latest` in a top-level directory where all git-projects live, this would indeed have the potential to destroy data. 
> until i'm able to push out a fix

Awesome, I think as long as we don't advertise the `npm create anywidget@latest` command, a fix is not urgent :) 

Enjoy the conference and also thanks for your great work! :)

**Comment by kolibril13** [comment]
Hi @manzt, I was wondering: is `npm create anywidget@latest` now save to use?

**Comment by manzt** [comment]
haven’t found the time to work on this yet. I can push a branch to anywidget if you’d be interested in working on it!

**Comment by kolibril13** [comment]
I can give it a try!
is this the branch? -> https://github.com/manzt/anywidget/tree/create-anywidget

And how do I develop it?

Is it 
```
cd packages/create-anywidget
npm install
node index.js
```
?

**Comment by manzt** [comment]
oh right! it's on main. Yup, that's exactly it. `node index.js` is what is executed with npx create anywidget.

**Comment by kolibril13** [comment]
> it's on main.

on main the folder is empty:
https://github.com/manzt/anywidget/tree/main/packages/create-anywidget

so I'll go with the branch https://github.com/manzt/anywidget/tree/create-anywidget then?

**Comment by manzt** [comment]
yes, sounds good!
